name: Test frontend
on:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t redvant/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true redvant/react-test npm test